- name : Install Mongodb
  hosts: 
  become: yes
  tasks:
   - name: Add MongoDB to yum repositories
     ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present
    
    - name: Start and enable Mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Change bind address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.0'
        replace: '0.0.0.0'

    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted
        

     